/** @format */

export const LATESTPRODUCT_LIST_REQUEST = "LATESTPRODUCT_LIST_REQUEST";
export const LATESTPRODUCT_LIST_SUCCESS = "LATESTPRODUCT_LIST_SUCCESS";
export const LATESTPRODUCT_LIST_FAIL = "LATESTPRODUCT_LIST_FAIL";

export const LATESTPRODUCT_DETAILS_REQUEST = "LATESTPRODUCT_DETAILS_REQUEST";
export const LATESTPRODUCT_DETAILS_SUCCESS = "LATESTPRODUCT_DETAILS_SUCCESS";
export const LATESTPRODUCT_DETAILS_FAIL = "LATESTPRODUCT_DETAILS_FAIL";


export const CREATE_LATEST_PRODUCT_REQUEST = 'CREATE_LATEST_PRODUCT_REQUEST'
export const CREATE_LATEST_PRODUCT_SUCCESS = 'CREATE_LATEST_PRODUCT_SUCCESS'
export const CREATE_LATEST_PRODUCT_FAIL = 'CREATE_LATEST_PRODUCT_FAIL'
export const CREATE_LATEST_PRODUCT_RESET = 'CREATE_LATEST_PRODUCT_RESET'

export const UPDATE_LATEST_PRODUCT_REQUEST = 'UPDATE_LATEST_PRODUCT_REQUEST'
export const UPDATE_LATEST_PRODUCT_SUCCESS = 'UPDATE_LATEST_PRODUCT_SUCCESS'
export const UPDATE_LATEST_PRODUCT_FAIL = 'UPDATE_LATEST_PRODUCT_FAIL'
export const UPDATE_LATEST_PRODUCT_RESET = 'UPDATE_LATEST_PRODUCT_RESET'


export const LATEST_PRODUCT_DELETE_REQUEST = 'LATEST_PRODUCT_DELETE_REQUEST'
export const LATEST_PRODUCT_DELETE_SUCCESS = 'LATEST_PRODUCT_DELETE_SUCCESS'
export const LATEST_PRODUCT_DELETE_FAIL = 'LATEST_PRODUCT_DELETE_FAIL'
export const LATEST_PRODUCT_DELETE_RESET = 'LATEST_PRODUCT_DELETE_RESET'


export const LATEST_PRODUCT_CATEGORY_REQUEST = 'LATEST_PRODUCT_CATEGORY_REQUEST'
export const LATEST_PRODUCT_CATEGORY_SUCCESS = 'LATEST_PRODUCT_CATEGORY_SUCCESS'
export const LATEST_PRODUCT_CATEGORY_FAIL = 'LATEST_PRODUCT_CATEGORY_FAIL'
export const LATEST_PRODUCT_CATEGORY_RESET = 'LATEST_PRODUCT_CATEGORY_RESET'


export const CREATE_LATEST_PRODUCT_COMMENT_REQUEST = 'CREATE_LATEST_PRODUCT_COMMENT_REQUEST'
export const CREATE_LATEST_PRODUCT_COMMENT_SUCCESS = 'CREATE_LATEST_PRODUCT_COMMENT_SUCCESS'
export const CREATE_LATEST_PRODUCT_COMMENT_FAIL = 'CREATE_LATEST_PRODUCT_COMMENT_FAIL'
export const CREATE_LATEST_PRODUCT_COMMENT_RESET = 'CREATE_LATEST_PRODUCT_COMMENT_RESET'