export const ORDER_LATEST_CREATE_REQUEST = 'ORDER_LATEST_CREATE_REQUEST'
export const ORDER_LATEST_CREATE_SUCCESS = 'ORDER_LATEST_CREATE_SUCCESS'
export const ORDER_LATEST_CREATE_FAIL = 'ORDER_LATEST_CREATE_FAIL'
export const ORDER_LATEST_CREATE_RESET = 'ORDER_LATEST_CREATE_RESET'


export const ORDER_LATEST_DETAILS_REQUEST = 'ORDER_LATEST_DETAILS_REQUEST'
export const ORDER_LATEST_DETAILS_SUCCESS = 'ORDER_LATEST_DETAILS_SUCCESS'
export const ORDER_LATEST_DETAILS_FAIL = 'ORDER_LATEST_DETAILS_FAIL'


export const ORDER_LATEST_PAY_REQUEST = 'ORDER_LATEST_PAY_REQUEST'
export const ORDER_LATEST_PAY_SUCCESS = 'ORDER_LATEST_PAY_SUCCESS'
export const ORDER_LATEST_PAY_FAIL = 'ORDER_LATEST_PAY_FAIL'
export const ORDER_LATEST_PAY_RESET = 'ORDER_LATEST_PAY_RESET'



export const ORDER_LATEST_LIST_REQUEST = 'ORDER_LATEST_LIST_REQUEST'
export const ORDER_LATEST_LIST_SUCCESS = 'ORDER_LATEST_LIST_SUCCESS'
export const ORDER_LATEST_LIST_FAIL = 'ORDER_LATEST_LIST_FAIL'

export const ALL_ORDER_LATEST_LIST_REQUEST = 'ALL_ORDER_LATEST_LIST_REQUEST'
export const ALL_ORDER_LATEST_LIST_SUCCESS = 'ALL_ORDER_LATEST_LIST_SUCCESS'
export const ALL_ORDER_LATEST_LIST_FAIL = 'ALL_ORDER_LATEST_LIST_FAIL'


export const ORDER_LATEST_DELETE_REQUEST = 'ORDER_LATEST_DELETE_REQUEST'
export const ORDER_LATEST_DELETE_SUCCESS = 'ORDER_LATEST_DELETE_SUCCESS'
export const ORDER_LATEST_DELETE_FAIL = 'ORDER_LATEST_DELETE_FAIL'
export const ORDER_LATEST_DELETE_RESET = 'ORDER_LATEST_DELETE_RESET'


export const ORDER_LATEST_DELIVERED_REQUEST = 'ORDER_LATEST_DELIVERED_REQUEST'
export const ORDER_LATEST_DELIVERED_SUCCESS = 'ORDER_LATEST_DELIVERED_SUCCESS'
export const ORDER_LATEST_DELIVERED_FAIL = 'ORDER_LATEST_DELIVERED_FAIL'
export const ORDER_LATEST_DELIVERED_RESET = 'ORDER_LATEST_DELIVERED_RESET'