/** @format */

export const RELATEDPRODUCT_LIST_REQUEST = "RELATEDPRODUCT_LIST_REQUEST";
export const RELATEDPRODUCT_LIST_SUCCESS = "RELATEDPRODUCT_LIST_SUCCESS";
export const RELATEDPRODUCT_LIST_FAIL = "RELATEDPRODUCT_LIST_FAIL";

export const RELATEDPRODUCT_DETAILS_REQUEST = "RELATEDPRODUCT_DETAILS_REQUEST";
export const RELATEDPRODUCT_DETAILS_SUCCESS = "RELATEDPRODUCT_DETAILS_SUCCESS";
export const RELATEDPRODUCT_DETAILS_FAIL = "RELATEDPRODUCT_DETAILS_FAIL";

export const CREATE_RELATED_PRODUCT_REQUEST = 'CREATE_RELATED_PRODUCT_REQUEST'
export const CREATE_RELATED_PRODUCT_SUCCESS = 'CREATE_RELATED_PRODUCT_SUCCESS'
export const CREATE_RELATED_PRODUCT_FAIL = 'CREATE_RELATED_PRODUCT_FAIL'
export const CREATE_RELATED_PRODUCT_RESET = 'CREATE_RELATED_PRODUCT_RESET'

export const UPDATE_RELATED_PRODUCT_REQUEST = 'UPDATE_RELATED_PRODUCT_REQUEST'
export const UPDATE_RELATED_PRODUCT_SUCCESS = 'UPDATE_RELATED_PRODUCT_SUCCESS'
export const UPDATE_RELATED_PRODUCT_FAIL = 'UPDATE_RELATED_PRODUCT_FAIL'
export const UPDATE_RELATED_PRODUCT_RESET = 'UPDATE_RELATED_PRODUCT_RESET'


export const RELATED_PRODUCT_DELETE_REQUEST = 'RELATED_PRODUCT_DELETE_REQUEST'
export const RELATED_PRODUCT_DELETE_SUCCESS = 'RELATED_PRODUCT_DELETE_SUCCESS'
export const RELATED_PRODUCT_DELETE_FAIL = 'RELATED_PRODUCT_DELETE_FAIL'
export const RELATED_PRODUCT_DELETE_RESET = 'RELATED_PRODUCT_DELETE_RESET'
